### ISSUE TITLE
Close files during unittest

### ISSUE THREAD

**Issue by oeysteinhansen** [sugarsweetrobotics/idl_parser#3]
All files in the unittest are opened but not closed. This gives warnings when running the unittests
idl_parser f9407b1
Python 3.6.2

**Comment by sugarsweetrobotics** [comment]
I added with open(....) as idlf block in test files. This can suppress the warning messages, right (8e7d5ea..fe0968d on master). Please give me feedbacks. Thank you for your nice contribution!!

**Comment by oeysteinhansen** [comment]
Thanks for implementing this issue.
Tested OK
idl_parser  fe0968d 
Python 3.6.2
Windows 7

You can Close the Issue when you feel it is apropriate.
