### ISSUE TITLE
Coveralls exeption during unittest

### ISSUE THREAD

**Issue by oeysteinhansen** [sugarsweetrobotics/idl_parser#4]
I do not have the Coveralls module installed.
Could you adde a try: except: pass block around the coveralls import statements. 

This allows the idl_parser module unittests to be run localy, also without internet connection. 

I run the unittests on windows with:
`py -m unittest tests.module_test`

idl_parser  f9407b1
Python 3.6.2

**Comment by sugarsweetrobotics** [comment]
Thank you for comment. Your opinion is quite convincing. I added try-except block on "d2032c3..8e7d5ea" commit. Please check and give me your feedback if possible. Thank you!

**Comment by oeysteinhansen** [comment]
Thanks for implementing this issue.
Tested OK
idl_parser  fe0968d 
Python 3.6.2
Windows 7

You can Close the Issue when you feel it is apropriate.
